import java.awt.Component;

public class NewJFrame extends javax.swing.JFrame {

    public NewJFrame() {
        initComponents();
        
        getRootPane().setDefaultButton(equal);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        calcbox = new javax.swing.JTextField();
        c = new javax.swing.JButton();
        n1 = new javax.swing.JButton();
        n2 = new javax.swing.JButton();
        n3 = new javax.swing.JButton();
        n4 = new javax.swing.JButton();
        n5 = new javax.swing.JButton();
        n6 = new javax.swing.JButton();
        n7 = new javax.swing.JButton();
        n8 = new javax.swing.JButton();
        n9 = new javax.swing.JButton();
        n0 = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        div = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        power = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        calcbox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        calcbox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calcbox.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(calcbox, gridBagConstraints);

        c.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c.setForeground(new java.awt.Color(255, 0, 0));
        c.setText("C");
        c.setEnabled(false);
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(c, gridBagConstraints);

        n1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n1.setText("1");
        n1.setEnabled(false);
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n1, gridBagConstraints);

        n2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n2.setText("2");
        n2.setEnabled(false);
        n2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n2, gridBagConstraints);

        n3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n3.setText("3");
        n3.setEnabled(false);
        n3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n3, gridBagConstraints);

        n4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n4.setText("4");
        n4.setEnabled(false);
        n4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n4, gridBagConstraints);

        n5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n5.setText("5");
        n5.setEnabled(false);
        n5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n5, gridBagConstraints);

        n6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n6.setText("6");
        n6.setEnabled(false);
        n6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n6, gridBagConstraints);

        n7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n7.setText("7");
        n7.setEnabled(false);
        n7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n7, gridBagConstraints);

        n8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n8.setText("8");
        n8.setEnabled(false);
        n8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n8, gridBagConstraints);

        n9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n9.setText("9");
        n9.setEnabled(false);
        n9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n9, gridBagConstraints);

        n0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        n0.setText("0");
        n0.setEnabled(false);
        n0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(n0, gridBagConstraints);

        plus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        plus.setForeground(new java.awt.Color(255, 0, 0));
        plus.setText("+");
        plus.setEnabled(false);
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(plus, gridBagConstraints);

        minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minus.setForeground(new java.awt.Color(255, 0, 0));
        minus.setText("-");
        minus.setEnabled(false);
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(minus, gridBagConstraints);

        multi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        multi.setForeground(new java.awt.Color(255, 0, 0));
        multi.setText("*");
        multi.setEnabled(false);
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(multi, gridBagConstraints);

        div.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        div.setForeground(new java.awt.Color(255, 0, 0));
        div.setText("/");
        div.setEnabled(false);
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(div, gridBagConstraints);

        dot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dot.setForeground(new java.awt.Color(255, 0, 0));
        dot.setText(".");
        dot.setEnabled(false);
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(dot, gridBagConstraints);

        equal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        equal.setForeground(new java.awt.Color(255, 0, 0));
        equal.setText("=");
        equal.setEnabled(false);
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(equal, gridBagConstraints);

        power.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        power.setForeground(new java.awt.Color(255, 51, 51));
        power.setText("POWER");
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(power, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed
        if (c.isEnabled()){
            calcbox.setText("        ");
            c.setEnabled(false);
            calcbox.setEnabled(false);
            div.setEnabled(false);
            dot.setEnabled(false);
            equal.setEnabled(false);
            minus.setEnabled(false);
            multi.setEnabled(false);
            n0.setEnabled(false);
            n1.setEnabled(false);
            n2.setEnabled(false);
            n3.setEnabled(false);
            n4.setEnabled(false);
            n5.setEnabled(false);
            n6.setEnabled(false);
            n7.setEnabled(false);
            n8.setEnabled(false);
            n9.setEnabled(false);
            plus.setEnabled(false);
        }else{
            c.setEnabled(true);
            calcbox.setEnabled(true);
            div.setEnabled(true);
            dot.setEnabled(true);
            equal.setEnabled(true);
            minus.setEnabled(true);
            multi.setEnabled(true);
            n0.setEnabled(true);
            n1.setEnabled(true);
            n2.setEnabled(true);
            n3.setEnabled(true);
            n4.setEnabled(true);
            n5.setEnabled(true);
            n6.setEnabled(true);
            n7.setEnabled(true);
            n8.setEnabled(true);
            n9.setEnabled(true);
            plus.setEnabled(true);
        }
    }//GEN-LAST:event_powerActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        calcbox.setText(calcbox.getText()+"1");
    }//GEN-LAST:event_n1ActionPerformed

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
        calcbox.setText(calcbox.getText()+"0");
    }//GEN-LAST:event_n0ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
        calcbox.setText(calcbox.getText()+"2");
    }//GEN-LAST:event_n2ActionPerformed

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
        calcbox.setText(calcbox.getText()+"3");
    }//GEN-LAST:event_n3ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
        calcbox.setText(calcbox.getText()+"4");
    }//GEN-LAST:event_n4ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
        calcbox.setText(calcbox.getText()+"5");
    }//GEN-LAST:event_n5ActionPerformed

    private void n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ActionPerformed
        calcbox.setText(calcbox.getText()+"6");
    }//GEN-LAST:event_n6ActionPerformed

    private void n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7ActionPerformed
        calcbox.setText(calcbox.getText()+"7");
    }//GEN-LAST:event_n7ActionPerformed

    private void n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8ActionPerformed
        calcbox.setText(calcbox.getText()+"8");
    }//GEN-LAST:event_n8ActionPerformed

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
        calcbox.setText(calcbox.getText()+"9");
    }//GEN-LAST:event_n9ActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        if (dotflag== false){
            calcbox.setText(calcbox.getText()+".");
            dotflag = true;
        }
    }//GEN-LAST:event_dotActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        number1=Double.valueOf(calcbox.getText());
        calcbox.setText("");
        dot.setEnabled(true);
        sign="add";
        
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        number1=Double.valueOf(calcbox.getText());
        calcbox.setText("");
        dot.setEnabled(true);
        sign="minus";
    }//GEN-LAST:event_minusActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        number1=Double.valueOf(calcbox.getText());
        calcbox.setText("");
        dot.setEnabled(true);
        sign="times";
    }//GEN-LAST:event_multiActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        number1=Double.valueOf(calcbox.getText());
        calcbox.setText("");
        dot.setEnabled(true);
        sign="divide";
    }//GEN-LAST:event_divActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        String temp=calcbox.getText();
        if(temp.isEmpty()){
            if(number1!=0){
                calcbox.setText(String.valueOf(number1));
            }else if(number1==0){
                calcbox.setText("0.0");
            }
        }else{
            number2=Double.valueOf(temp);
            if(sign.contentEquals("add")) result=number1+number2;
            else if(sign.contentEquals("minus")) result=number1-number2;
            else if(sign.contentEquals("times")) result=number1*number2;
            else if(sign.contentEquals("divide")) {
                if(number2!=0){
                    result=number1/number2;
                }else {
                    errorflag=true;
                }
            }
            if(errorflag==false){
                resulttxt=String.valueOf(result);
                calcbox.setText(resulttxt);
            }else calcbox.setText("ERROR");
        }
    }//GEN-LAST:event_equalActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        calcbox.setText("");
        dot.setEnabled(true);
        errorflag=false;
        number1=0;
        number2=0;
        result=0;
    }//GEN-LAST:event_cActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
        boolean dotflag=false;
        double number1=0;
        double number2=0;
        double result=0;
        String sign =null;
        boolean errorflag=false;
        String resulttxt="          ";
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c;
    private javax.swing.JTextField calcbox;
    private javax.swing.JButton div;
    private javax.swing.JButton dot;
    private javax.swing.JButton equal;
    private javax.swing.JButton minus;
    private javax.swing.JButton multi;
    private javax.swing.JButton n0;
    private javax.swing.JButton n1;
    private javax.swing.JButton n2;
    private javax.swing.JButton n3;
    private javax.swing.JButton n4;
    private javax.swing.JButton n5;
    private javax.swing.JButton n6;
    private javax.swing.JButton n7;
    private javax.swing.JButton n8;
    private javax.swing.JButton n9;
    private javax.swing.JButton plus;
    private javax.swing.JButton power;
    // End of variables declaration//GEN-END:variables

    
}
